/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import General.Configuration;
import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jithinpv
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadIcons();
        
    }

    private void loadIcons() {
        Configuration.setIconOnLabel("logout.png", jLabel8);
         Configuration.setIconOnLabel("home.jpg", jLabel4);
        Configuration.setIconOnButton("view-subscription-button.png", jButton5);
        Configuration.setIconOnButton("create-new-presentation.png", jButton6);
        Configuration.setIconOnButton("launch-presentation.png", jButton7);
        Configuration.setIconOnButton("launch-samples.png", jButton8);
        Configuration.setIconOnButton("add.png", jButton4);
        Configuration.setIconOnButton("hierarchy.png", jButton13);
        
       


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        countries_list = new java.awt.List();
        organization_list = new java.awt.List();
        states_list = new java.awt.List();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Countries");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 73, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("States");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 73, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Organization");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 73, -1));

        countries_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                countries_listItemStateChanged(evt);
            }
        });
        countries_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countries_listActionPerformed(evt);
            }
        });
        getContentPane().add(countries_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 54, 122, 164));
        getContentPane().add(organization_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 54, 122, 164));

        states_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                states_listItemStateChanged(evt);
            }
        });
        getContentPane().add(states_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 54, 122, 164));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 228, 90, -1));

        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 228, 87, -1));

        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 228, 80, -1));

        jButton4.setToolTipText("CREATE MULTICAST SUBSCRIPTION");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 308, 86, 72));

        jButton5.setToolTipText("VIEW SUBSCRIPTION");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 308, 75, 72));

        jButton6.setToolTipText("CREATE NEW PRESENTATION");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 308, 91, 67));

        jButton7.setToolTipText("LAUNCH A PRESENTATION");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 398, 92, 69));

        jLabel8.setToolTipText("Logout");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 11, 26, 28));

        jButton9.setText("Manage");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 259, 90, -1));

        jButton10.setText("Manage");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 257, -1, -1));

        jButton11.setText("Manage");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 259, 87, -1));

        jButton8.setToolTipText("LAUNCH SAMPLES");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 398, 69, 69));

        jButton13.setToolTipText("HEIRARCHICAL VIEW");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 398, 81, 69));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 520, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countries_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countries_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countries_listActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateCountry createCountry = new CreateCountry();
        createCountry.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateState createstate = new CreateState();
        createstate.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateOrganization createOrganization = new CreateOrganization();
        createOrganization.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ChooseCountries chooseCountries = new ChooseCountries();
        chooseCountries.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewSubscription viewSubscription = new ViewSubscription();
        viewSubscription.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CreateNewPresentation createNewPresentation = new CreateNewPresentation();
        createNewPresentation.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LaunchPresentation launchPresentation = new LaunchPresentation();
        launchPresentation.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
        AdminLogin adminLogin = new AdminLogin();
        adminLogin.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void loadAllCountries() {
        Dbcon dbcon = new Dbcon();
        ResultSet rs = dbcon.select("select * from tbl_country");
        try {
            while (rs.next()) {
                String countryName = rs.getString("country_name");
                System.out.println(countryName);
                countries_list.addItem(countryName);
            }
        } catch (SQLException ex) {

            ex.printStackTrace();
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        loadAllCountries();
    }//GEN-LAST:event_formWindowOpened

    private void countries_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_countries_listItemStateChanged
        states_list.removeAll();
        organization_list.removeAll();
        String selecteditem = countries_list.getSelectedItem();

        String countryId = "";
        Dbcon dbcon = new Dbcon();
        ResultSet rs = dbcon.select("select country_id from tbl_country where country_name='" + selecteditem + "'");

        try {
            if (rs.next()) {
                countryId = rs.getString("country_id");
                System.out.println(countryId);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        ResultSet r = dbcon.select("select state_name from tbl_state where country='" + countryId + "'");
        try {
            while (r.next()) {
                String states = r.getString("state_name");
                System.out.println(states);
                states_list.addItem(states);

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_countries_listItemStateChanged

    private void states_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_states_listItemStateChanged
        // TODO add your handling code here:
        organization_list.removeAll();
        Dbcon dbcon = new Dbcon();
        String countryId = "", stateId = "";
        String selectedState = states_list.getSelectedItem();
        String selectedCountry = countries_list.getSelectedItem();
        ResultSet rs = dbcon.select("select country_id from tbl_country where country_name='" + selectedCountry + "'");

        try {
            if (rs.next()) {
                countryId = rs.getString("country_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        ResultSet r = dbcon.select("select state_id from tbl_state where state_name='" + selectedState + "' and country='" + countryId + "'");

        try {
            if (r.next()) {
                stateId = r.getString("state_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        ResultSet rst = dbcon.select("select organization_name from tbl_organization where country='" + countryId + "' and state='" + stateId + "'");
        try {
            while (rst.next()) {
                String orgs = rst.getString("organization_name");
                System.out.println(orgs);
                organization_list.addItem(orgs);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_states_listItemStateChanged

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ManageCountry manageCountry = new ManageCountry();
        manageCountry.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ManageState manageState = new ManageState();
        manageState.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ManageOrganisation manageOrganisation = new ManageOrganisation();
        manageOrganisation.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    // TODO add your handling code here:
    ViewAllOrganisations viewAllOrganisations = new ViewAllOrganisations();
    viewAllOrganisations.setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List countries_list;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private java.awt.List organization_list;
    private java.awt.List states_list;
    // End of variables declaration//GEN-END:variables
}
