/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import General.Configuration;
import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jithinpv
 */
public class ChooseStates3 extends javax.swing.JFrame {

    public static ArrayList<String> countryIds;

    /**
     * Creates new form ChooseStates
     */
    public ChooseStates3() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadIcons();
        loadAllStates(countryIds);
    }

    public ChooseStates3(ArrayList<String> countryIds) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.countryIds = countryIds;
        loadIcons();
        loadAllStates(countryIds);
    }

    private void loadIcons() {
        Configuration.setIconOnLabel("leftArrow.png", jLabel4);
        Configuration.setIconOnLabel("rightArrow.png", jLabel5);
        Configuration.setIconOnLabel("choose.jpg", jLabel6);

    }

    private void loadAllStates(ArrayList<String> countryIds) {
        //System.out.println(countryIds);
        Dbcon dbcon = new Dbcon();
        String string = "";
        for (int i = 0; i < countryIds.size(); i++) {

            countryIds.get(i);
            if (i == (countryIds.size() - 1)) {
                string = string + countryIds.get(i);
            } else {
                string = string + countryIds.get(i) + ",";
            }
            // System.out.println(string);
        }
        String query = "select state_name from tbl_state where country in (" + string + ") ";
        //System.out.println(query);
        ResultSet rs = dbcon.select(query);
        try {
            while (rs.next()) {
                String stateName = rs.getString("state_name");
                state_list.addItem(stateName);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        state_list = new java.awt.List();
        selected_states = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose States:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 28, 164, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("All States");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 73, 58, -1));
        getContentPane().add(state_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 105, 111, 157));
        getContentPane().add(selected_states, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 105, 111, 157));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("selected States");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 73, 95, -1));

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 286, -1, -1));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 286, -1, -1));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 192, 146, 54));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 120, 146, 54));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 480, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<String> generateStateIds() {
        ArrayList<String> stateIds = new ArrayList<String>();
        String[] items = selected_states.getItems();

        if (items.length > 0) {
            Dbcon dbcon = new Dbcon();
            for (int i = 0; i < items.length; i++) {
                // System.out.println(items[i]);
                ResultSet rs = dbcon.select("select state_id from tbl_state where state_name='" + items[i] + "'");
                try {
                    if (rs.next()) {
                        stateIds.add(rs.getString("state_id"));
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
        System.out.println(stateIds);
        return stateIds;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ChooseCountries chooseCountries = new ChooseCountries();
        chooseCountries.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

         ArrayList<String> stateIds = generateStateIds();
          if (stateIds.size() > 0) {
              Dbcon dbcon=new Dbcon();
             
        this.dispose();
        ChooseOrganization chooseOrganization=new ChooseOrganization(stateIds);
        chooseOrganization.setVisible(true);
          }else {
            JOptionPane.showMessageDialog(rootPane, "select state");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if (state_list.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(rootPane, "select a state");
        } else {
            String selectedItem = state_list.getSelectedItem();
            selected_states.addItem(selectedItem);
            state_list.remove(selectedItem);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if (selected_states.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(rootPane, "select a state");
        } else {
            String selectedItem = selected_states.getSelectedItem();
            selected_states.remove(selectedItem);
            state_list.addItem(selectedItem);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseStates3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseStates3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseStates3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseStates3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ChooseStates3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.List selected_states;
    private java.awt.List state_list;
    // End of variables declaration//GEN-END:variables
}
