/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import General.Configuration;
import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jithinpv
 */
public class ChooseOrganization extends javax.swing.JFrame {

    public static ArrayList<String> stateIds;

    /**
     * Creates new form ChooseOrganization
     */
    public ChooseOrganization() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadIcons();
        loadAllOrganization(stateIds);
        
    }

    public ChooseOrganization(ArrayList<String> stateIds) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.stateIds = stateIds;
        loadIcons();
        loadAllOrganization(stateIds);
        
    }

    private void loadIcons() {
        Configuration.setIconOnLabel("leftArrow.png", jLabel4);
        Configuration.setIconOnLabel("rightArrow.png", jLabel5);
        Configuration.setIconOnLabel("choose.jpg", jLabel6);
    }

    private void loadAllOrganization(ArrayList<String> stateIds) {
        System.out.println(stateIds);
        Dbcon dbcon = new Dbcon();
        String string = "";
        for (int i = 0; i < stateIds.size(); i++) {

            stateIds.get(i);
            if (i == (stateIds.size() - 1)) {
                string = string + stateIds.get(i);
            } else {
                string = string + stateIds.get(i) + ",";
            }
            //  System.out.println(string);
        }
        String query = "SELECT *, state.state_name,country.country_name FROM tbl_organization AS org ,tbl_state AS state , tbl_country AS country WHERE org.state IN (" + string + ") AND state.state_id = org.state AND country.country_id = org.country;";
        System.out.println(query);
        ResultSet rs = dbcon.select(query);
        try {
            while (rs.next()) {
                String orgName = rs.getString("organization_name");
                org_list.addItem(orgName + "-" + rs.getString("state_name") + "-" + rs.getString("country_name"));
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        org_list = new java.awt.List();
        selected_org = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose Organization:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 27, 239, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("All Organization");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 80, 95, -1));
        getContentPane().add(org_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, 137, 127));
        getContentPane().add(selected_org, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 104, 122, 127));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selected Organization");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 80, -1, -1));

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 249, 74, -1));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 249, -1, -1));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 177, 146, 54));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 104, 146, 54));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 610, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ChooseStates3 chooseStates = new ChooseStates3();
       chooseStates.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private ArrayList<String> generateBuffer() {
        ArrayList<String> organisations = new ArrayList<String>();
        String[] items = selected_org.getItems();
        if (items.length > 0) {
            for (int i = 0; i < items.length; i++) {
                organisations.add(items[i]);
            }
        } else {
        }

        return organisations;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> buffer = generateBuffer();
        if (buffer.size() != 0) {
            this.dispose();
            CreateMulticastSubscription createMulticastSubscription = new CreateMulticastSubscription(buffer);
            createMulticastSubscription.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please select atleast one organisation");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        if (org_list.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(rootPane, "select a organization");
        } else {
            String selectedItem = org_list.getSelectedItem();
            selected_org.addItem(selectedItem);
            org_list.remove(selectedItem);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        if (selected_org.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(rootPane, "select a organization");
        } else {
            String selectedItem = selected_org.getSelectedItem();
            selected_org.remove(selectedItem);
            org_list.addItem(selectedItem);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseOrganization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseOrganization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseOrganization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseOrganization.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ChooseOrganization().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.List org_list;
    private java.awt.List selected_org;
    // End of variables declaration//GEN-END:variables
}
