/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HerarchicalTree.java
 *
 * Created on Sep 28, 2016, 10:52:57 PM
 */
package view;

import General.Configuration;
import db.Dbcon;
import java.sql.ResultSet;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author kakes
 */
public class HerarchicalTree extends javax.swing.JFrame {

    /** Creates new form HerarchicalTree */
    public HerarchicalTree() {
        initComponents();
        Configuration.setIconOnLabel("heirarchy-background.jpg", jLabel2);
        loadTree2();
        expandNodes();
        this.setLocationRelativeTo(null);
    }
    
        private void loadTree2() {
        String sql = "SELECT state.state_name  , cnt.country_name, org.* "
                + " FROM tbl_organization AS org ,"
                + " tbl_country AS cnt , "
                + " tbl_state AS state "
                + " WHERE org.country = cnt.country_id AND "
                + " org.state = state.state_id;";
        //ResultSet select = new Dbcon().select(sql);

        Dbcon dbcon1 = new Dbcon();
        Dbcon dbcon2 = new Dbcon();
        Dbcon dbcon3 = new Dbcon();

        String sql1 = "select * from tbl_country ";
        ResultSet rs1 = dbcon1.select(sql1);
        try {

            DefaultTreeModel model = (DefaultTreeModel) jTree2.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();

            while (rs1.next()) {
                String country_name = rs1.getString("country_name");
                String country_id = rs1.getString("country_id");
                DefaultMutableTreeNode defaultMutableTreeNode1 = new DefaultMutableTreeNode(country_name);
                String sql2 = "select * from tbl_state where country=" + country_id;

                ResultSet rs2 = dbcon2.select(sql2);
                while (rs2.next()) {
                    String state_name = rs2.getString("state_name");
                    String state_id = rs2.getString("state_id");

                    DefaultMutableTreeNode defaultMutableTreeNode2 = new DefaultMutableTreeNode(state_name);

                    defaultMutableTreeNode1.add(defaultMutableTreeNode2);

                    String sql3 = "select * from tbl_organization where state=" + state_id;
                    ResultSet rs3 = dbcon3.select(sql3);

                    while (rs3.next()) {
                        String organization_name = rs3.getString("organization_name");
                        DefaultMutableTreeNode defaultMutableTreeNode3 = new DefaultMutableTreeNode(organization_name);
                        defaultMutableTreeNode2.add(defaultMutableTreeNode3);
                    }
//                    defaultMutableTreeNode1.add(defaultMutableTreeNode2);
                }
                root.add(defaultMutableTreeNode1);
                root.setUserObject("multicast");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        String sql2 = "select * from tbl_organization";
        jTree2.repaint();
        jTree2.revalidate();

    }

    private void expandNodes() {
        for (int i = 0; i < jTree2.getRowCount(); i++) {
            jTree2.expandRow(i);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 30, 386, 640));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 647, -1, -1));

        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 560, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    dispose();
    new AdminHome().setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HerarchicalTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HerarchicalTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HerarchicalTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HerarchicalTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HerarchicalTree().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree2;
    // End of variables declaration//GEN-END:variables
}
