/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import General.Configuration;
import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Jithinpv
 */
public class HerarchicalTree extends javax.swing.JFrame {

    /**
     * Creates new form HerarchicalTree
     */
    public HerarchicalTree() {
        initComponents();
         loadTree();
        this.setLocationRelativeTo(null);
         Configuration.setIconOnLabel("heirarchy-background.jpg", jLabel2);
    }
    private void loadTree(){
   
        DefaultTreeModel model = (DefaultTreeModel) jTree2.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
       
            
            
        ArrayList<String> arr = new ArrayList<>();
        
        
         Dbcon dbcon = new Dbcon();
        ResultSet rs = dbcon.select("select * from tbl_country");
        try {
            while (rs.next()) {
                String countryName = rs.getString("country_name");
                
                arr.add(countryName);
                System.out.println(countryName);
                System.out.println(arr);
            }
        } catch (SQLException ex) {

            ex.printStackTrace();
        }
       
       
        ArrayList<String> arr2 = new ArrayList<>();
        
        
        ResultSet r = dbcon.select("select * from tbl_state");
        try {
            while (r.next()) {
                String stateName = r.getString("state_name");
              
                arr2.add(stateName);
                  System.out.println(stateName);
                  System.out.println(arr2);
            }
        } catch (SQLException ex) {

            ex.printStackTrace();
        }
 
        ArrayList<String> arr3 = new ArrayList<>();
             
        ResultSet rst = dbcon.select("select * from tbl_organization");
        try {
            while (rst.next()) {
                String orgName = rst.getString("organization_name");
               
                arr3.add(orgName);
                 System.out.println(orgName);
                 System.out.println(arr3);
            }
        } catch (SQLException ex) {

            ex.printStackTrace();
        }      
       
        for(String ar : arr) {
            DefaultMutableTreeNode defaultMutableTreeNode = new DefaultMutableTreeNode(ar);
            for (String ar2 : arr2) {
                DefaultMutableTreeNode defaultMutableTreeNode2 = new DefaultMutableTreeNode(ar2);
                for (String ar3 : arr3) {
                    System.err.println("adding " + ar3);
                    DefaultMutableTreeNode defaultMutableTreeNode3 = new DefaultMutableTreeNode(ar3);
                    defaultMutableTreeNode2.add(defaultMutableTreeNode3);
                }
                defaultMutableTreeNode.add(defaultMutableTreeNode2);               
            }
            root.add(defaultMutableTreeNode);
        }
        jTree2.repaint();
        jTree2.revalidate();
        root.setUserObject("multicast");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree2.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree2.setMaximumSize(new java.awt.Dimension(59, 50));
        jTree2.setPreferredSize(new java.awt.Dimension(59, 50));
        jScrollPane2.setViewportView(jTree2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 54, 278, 208));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MULTICAST HEIRARCHY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 240, 25));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HerarchicalTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HerarchicalTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HerarchicalTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HerarchicalTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HerarchicalTree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree2;
    // End of variables declaration//GEN-END:variables
}
