/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import General.Configuration;
import db.Dbcon;
import java.sql.ResultSet;

/**
 *
 * @author Jithinpv
 */
public class LaunchPresentation extends javax.swing.JFrame {

    /**
     * Creates new form LaunchPresentation
     */
    String defaultPresentationName = null;

    public LaunchPresentation() {
        initComponents();
        this.setLocationRelativeTo(null);
        launch_button.setEnabled(false);
        loadPresentations();
          Configuration.setIconOnLabel("launch-present.jpg", jLabel4);
    }

    public LaunchPresentation(String presentationName) {
        initComponents();
        this.setLocationRelativeTo(null);
        launch_button.setEnabled(false);
        defaultPresentationName = presentationName;
        loadPresentations();
          Configuration.setIconOnLabel("launch-present.jpg", jLabel4);
    }

    private void loadPresentations() {
        Dbcon dbcon = new Dbcon();
        String sql = "select * from tbl_create_presentation order by id desc";
        ResultSet rs = dbcon.select(sql);
        boolean presentationFound = false;
        try {
            presentation_name_combo.removeAllItems();
            while (rs.next()) {
                presentation_name_combo.addItem(rs.getString("name"));
                presentationFound = true;
            }
            if (presentationFound) {
                if (defaultPresentationName != null) {
                    presentation_name_combo.setSelectedItem(defaultPresentationName);
                }
                loadMulticastList();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadMulticastList() {
        Dbcon dbcon = new Dbcon();
        String sql = "select * from tbl_subscription order by id desc";
        ResultSet rs = dbcon.select(sql);
        try {
            boolean multicastListFound = false;
            multicast_list_combo.removeAllItems();
            while (rs.next()) {
                multicast_list_combo.addItem(rs.getString("subscription_name"));
                multicastListFound = true;
            }
            if (multicastListFound) {
                launch_button.setEnabled(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        presentation_name_combo = new javax.swing.JComboBox();
        launch_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        multicast_list_combo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("LAUNCH PRESENTATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 21, 167, -1));

        jLabel2.setText("Choose Presentation:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 71, 137, 25));

        getContentPane().add(presentation_name_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 71, 134, 25));

        launch_button.setText("LAUNCH");
        launch_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launch_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(launch_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 191, 93, 25));

        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 191, 78, 25));

        jLabel3.setText("Choose Multicast:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 126, 137, 25));

        getContentPane().add(multicast_list_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 126, 134, 25));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 380, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AdminHome adminHome = new AdminHome();
        adminHome.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

private void launch_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launch_buttonActionPerformed

    this.dispose();
    String presentation = presentation_name_combo.getSelectedItem().toString();
    String multicastListName = multicast_list_combo.getSelectedItem().toString();
    new LaunchingFrame(presentation, multicastListName).setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_launch_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaunchPresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaunchPresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaunchPresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaunchPresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LaunchPresentation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton launch_button;
    private javax.swing.JComboBox multicast_list_combo;
    private javax.swing.JComboBox presentation_name_combo;
    // End of variables declaration//GEN-END:variables
}
