/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import General.Configuration;
import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jithinpv
 */
public class ManageState extends javax.swing.JFrame {

    /**
     * Creates new form ManageState
     */
    public ManageState() {
        initComponents();
        loadAllStates();
        this.setLocationRelativeTo(null);
        Configuration.setIconOnLabel("create.jpg", jLabel4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_states = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        edit_button = new javax.swing.JButton();
        save_button = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_states.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "STATES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_states.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_statesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_statesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_states);
        if (tbl_states.getColumnModel().getColumnCount() > 0) {
            tbl_states.getColumnModel().getColumn(0).setMinWidth(50);
            tbl_states.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_states.getColumnModel().getColumn(0).setMaxWidth(50);
            tbl_states.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 194, 188));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 67, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DESCRIPTION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 118, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 64, 152, -1));

        description.setColumns(20);
        description.setRows(5);
        jScrollPane2.setViewportView(description);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 102, 152, 72));

        edit_button.setText("EDIT");
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(edit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 205, -1, -1));

        save_button.setText("SAVE");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 205, -1, -1));

        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 205, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MANAGE STATES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 19, 160, -1));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 510, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_statesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_statesMouseClicked
        // TODO add your handling code here:
         if (tbl_states.getSelectedRow() >= 0) {
            String state_id = tbl_states.getValueAt(tbl_states.getSelectedRow(), 0).toString();
            Dbcon dbcon = new Dbcon();
            ResultSet rs = dbcon.select("select * from tbl_state where state_id='" + state_id + "' ");

            try {
                if (rs.next()) {
                    name.setText(rs.getString("state_name"));
                    description.setText(rs.getString("description"));
                    edit_button.setEnabled(true);
                    save_button.setEnabled(true);
                }
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_tbl_statesMouseClicked

    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
        // TODO add your handling code here:
        name.setEditable(true);
        description.setEditable(true);
    }//GEN-LAST:event_edit_buttonActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        // TODO add your handling code here:
         String state_id = tbl_states.getValueAt(tbl_states.getSelectedRow(), 0).toString(); 
        String state_name= name.getText();
        String desc=description.getText();
         if (state_name.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Enter name");
        } else if (desc.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Enter description");
        }else{
            Dbcon dbcon=new Dbcon();
        dbcon.update("update tbl_state set state_name='"+state_name+"', description='"+desc+"' where state_id='"+state_id+"'");
        }
        
    }//GEN-LAST:event_save_buttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        AdminHome home=new AdminHome();
        home.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbl_statesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_statesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_statesMouseEntered

     private void loadAllStates() {
        DefaultTableModel model = (DefaultTableModel) tbl_states.getModel();
        String arr[] = new String[3];
        Dbcon dbcon = new Dbcon();
        ResultSet rs = dbcon.select("select * from tbl_state");
        try {
            while (rs.next()) {
                String stateName = rs.getString("state_name");
                String state_id = rs.getString("state_id");
                System.out.println(stateName);
                arr[0] = state_id;
                arr[1] = stateName;
                model.addRow(arr);
                name.setEditable(false);
                description.setEditable(false);
                edit_button.setEnabled(false);
                save_button.setEnabled(false);

            }
        } catch (SQLException ex) {

            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageState.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageState.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageState.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageState.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageState().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea description;
    private javax.swing.JButton edit_button;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JButton save_button;
    private javax.swing.JTable tbl_states;
    // End of variables declaration//GEN-END:variables
}
