/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import General.Configuration;
import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jithinpv
 */
public class ViewSubscription extends javax.swing.JFrame {

    /**
     * Creates new form ViewSubscription
     */
    public ViewSubscription() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadAllSubscription();
         Configuration.setIconOnLabel("view_subscription.jpg", jLabel3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subscription_table = new javax.swing.JTable();
        companids_list = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ALL SUBSCRIPTIONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 24, 174, -1));

        subscription_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SUBSCRIPTION NAME", "DESCRIPTION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        subscription_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subscription_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subscription_table);
        if (subscription_table.getColumnModel().getColumnCount() > 0) {
            subscription_table.getColumnModel().getColumn(0).setMinWidth(50);
            subscription_table.getColumnModel().getColumn(0).setPreferredWidth(50);
            subscription_table.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, 375, 114));
        getContentPane().add(companids_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 73, 126, 114));

        jLabel2.setText("Companies:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 49, 85, -1));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 220, 116, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 580, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        AdminHome adminHome=new AdminHome();
        adminHome.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void subscription_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subscription_tableMouseClicked
        // TODO add your handling code here:
        
        if(subscription_table.getSelectedRow()>=0) {
            String id = subscription_table.getValueAt(subscription_table.getSelectedRow(), 0).toString();
            Dbcon dbcon = new Dbcon();
            String sql = "select org.organization_name,sub_list.* from tbl_organization as org ,tbl_subscription_list as sub_list,tbl_subscription as tbl_sub where tbl_sub.id=sub_list.subscription_id and org.organization_id=sub_list.organization_id and tbl_sub.id='"+id+"' ";
            ResultSet rs=dbcon.select(sql);
            try {
                companids_list.clear();
                while(rs.next()){
                    companids_list.addItem(rs.getString("organization_name"));
                
            }
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
        
        
    }//GEN-LAST:event_subscription_tableMouseClicked

    private void loadAllSubscription(){
        Dbcon dbcon=new Dbcon();
        DefaultTableModel model = (DefaultTableModel) subscription_table.getModel();
         String arr[] = new String[3];
        ResultSet rs=dbcon.select("select * from tbl_subscription");
        try {
            while(rs.next()){
                String sub_id=rs.getString("id");
                String sub_name=rs.getString("subscription_name");
                String sub_description=rs.getString("description");
                arr[0]=sub_id;
                arr[1]=sub_name;
                arr[2]=sub_description;
                model.addRow(arr);
            }
        } catch (SQLException ex) {
           ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSubscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List companids_list;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable subscription_table;
    // End of variables declaration//GEN-END:variables
}
