/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewAllOrganisations.java
 *
 * Created on Sep 23, 2016, 10:59:49 PM
 */
package view;

import db.Dbcon;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kakes
 */
public class ViewAllOrganisations extends javax.swing.JFrame {

    /** Creates new form ViewAllOrganisations */
    public ViewAllOrganisations() {
        initComponents();
        loadAllOrganisation();
    }

    private void loadAllOrganisation() {
        try {
            String str = "select * from tbl_organization order by organization_id desc";
            ResultSet rs = new Dbcon().select(str);
            String arr[] = new String[10];
            DefaultTableModel model = (DefaultTableModel) all_organisation.getModel();
            int count = 0;
            while (rs.next()) {

                String organization_id = rs.getString("organization_id");
                String organization_name = rs.getString("organization_name");
                String country = rs.getString("country");
                String state = rs.getString("state");
                String ip_address = rs.getString("ip_address");
                String port = rs.getString("port");
                count++;
                arr[0] = count + "";
                arr[1] = organization_name;
                arr[2] = state;
                arr[3] = country;
                arr[4] = ip_address;
                arr[5] = port;
                arr[6] = organization_id;

                model.addRow(arr);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        all_organisation = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        all_organisation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Name", "State", "Country", "IP Address", "Port", "org_id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(all_organisation);
        all_organisation.getColumnModel().getColumn(0).setMinWidth(50);
        all_organisation.getColumnModel().getColumn(0).setPreferredWidth(50);
        all_organisation.getColumnModel().getColumn(0).setMaxWidth(50);
        all_organisation.getColumnModel().getColumn(6).setMinWidth(0);
        all_organisation.getColumnModel().getColumn(6).setPreferredWidth(0);
        all_organisation.getColumnModel().getColumn(6).setMaxWidth(0);

        jButton1.setText("Launch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    if (all_organisation.getSelectedRow() > 0) {
        String organisation_id = all_organisation.getValueAt(all_organisation.getSelectedRow(), 6).toString();
        System.out.println("organisation_id " + organisation_id);
        ResultSet rs = new Dbcon().select("select * from organisation_hotline where organisation_id=" + organisation_id.trim());
        try {
            if (rs.next()) {
                // already there , check if offline or online
                String status_code = rs.getString("status_code");
                if (status_code.trim().equals("2")) {
                    // user is offline
                    int updated = new Dbcon().update("update organisation_hotline set status_code=1 where organisation_id=" + organisation_id);
                    if (updated > 0) {
                         // launch organisation listner
                        OrganisationClient organisationClient =  new OrganisationClient();
                        organisationClient.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Could not launch, please try again later");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Organisation in already active");
                }
            } else {
                    // not there yet, add it
                    int insert = new Dbcon().insert("insert into organisation_hotline (organisation_id,status_code) values ("+organisation_id+" ,1)");
                    if(insert> 0) {
                        // launch organisation listner
                        OrganisationClient organisationClient = new OrganisationClient();
                        organisationClient.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Could not launch, please try again later");
                    }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    } else {
        JOptionPane.showMessageDialog(rootPane, "Please select an organisation to launch");
    }




    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllOrganisations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllOrganisations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllOrganisations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllOrganisations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ViewAllOrganisations().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable all_organisation;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
